### ISSUE TITLE
DataChannel - Is the RTCDataChannel supported?

### ISSUE THREAD

**Issue by whydna** [perchco/perchrtc#28]
I'm trying to use the RTCDataChannel in the nighthawk build, but it doesn't seem to be fully supported?
- The bufferedAmount property always seems to be zero.
- Doesn't seem to be a way to configure the channel to be in `reliable` mode - the `RTCDataChannelInit` doesn't have this property, and `RTCDataChannel.isReliable` is readonly.
- Setting `maxRetransmits` results in a crash (although I believe this is a chrome Issue)

Any advice?

**Comment by ceaglest** [comment]
@whydna Unfortunately I can't offer too much advice because I haven't tried this myself. I know that the offers/answers are generated with the optional `internalSctpDataChannels` constraint, so in theory this should be enough to get things started. Also, later versions of Chrome probably have better support than m45.

Are you calling:

```
- (RTCDataChannel*)createDataChannelWithLabel:(NSString*)label
                                       config:(RTCDataChannelInit*)config;
```

Before creating offers/answers? If you don't already have a channel created then the SDPs will not reflect this, and the channel will not be negotiated regardless of the optional constraint added.

**Comment by whydna** [comment]
@ceaglest Just wanted to reply here and say it works as expected.

Thanks!
