### ISSUE TITLE
Linker error while using code in my own project.

### ISSUE THREAD

**Issue by difujia** [perchco/perchrtc#6]
![image](https://cloud.githubusercontent.com/assets/2255369/8105405/7b9e5c18-106b-11e5-8b42-db0e3042388e.png)

Hi,

Thank you for the contribution. This project helped a lot in solving my webrtc problem.
Please see the picture above. I'm using the code in my own project, and the linker error suddenly occured. I'm sure I've added the webrtc compiled library in my library search path. I'm just wondering whether the project build setting was changed somewhere in order to build perch. Please help, thank you.

**Comment by ceaglest** [comment]
Hi Difujia,

Thanks for the feedback. Unfortunately, the PerchRTC classes are not setup to be easily used outside of the sample app yet (Would you be interested in this? See #7).

However, I'll see what I can do to help. The big issue when building PerchRTC in your own project is CaptureKit. Since we are subclassing C++ WebRTC classes within our project, the nighthawk-webrtc build includes their C++ capture headers. Besides the headers and defines (in nighthawk-webrtc) you also need to add the `-fno-rtti` compiler flag to PHVideoCaptureKit, and PHVideoCaptureBridge (see screenshot from the PerchRTC sample project).

![perchrtc build settings](https://cloud.githubusercontent.com/assets/1302577/8114329/ae735cda-1028-11e5-9c94-1928854618d3.png)

Hope this helps,
Chris

**Comment by difujia** [comment]
Great, that works, thanks. I will look into wrapping this into a pod later.

**Comment by ceaglest** [comment]
No worries about the pod spec ticket, I self assigned it :) We are going to land a few more bug fixes and enhancements before dealing with class prefixes and packaging the code up for reuse.

Closing this issue.
